databases:
  - name: test_app
    databaseName: test_app
    user: test_app

services:
  - type: web
    name: test_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
